/*DROP DATABASE NASCE;
CREATE DATABASE NASCE;*/
USE NASCE;

/*
CREATE TABLE SCHOOL(
    SchoolID int AUTO_INCREMENT PRIMARY KEY,
    Name varchar(90),
    State varchar(2),
    Center varchar(100)
);

CREATE TABLE SCHOOL_ASSOCIATION (
    AssociationID int AUTO_INCREMENT PRIMARY KEY,
    AssociationName varchar(25)
);

CREATE TABLE ASSOCIATED_WITH (
    AssociationID int,
    SchoolID int,
    FOREIGN KEY (AssociationID) REFERENCES SCHOOL_ASSOCIATION (AssociationID),
	FOREIGN KEY (SchoolID) REFERENCES SCHOOL (SchoolID)
);

CREATE TABLE SCHOOL_QUOTE (
    Amount VARCHAR(25),
    SchoolID int,
	FOREIGN KEY (SchoolID) REFERENCES SCHOOL (SchoolID)
);

CREATE TABLE SCHOOL_NEXT_ADMINISTRATION (
    Date VARCHAR(60),
    SchoolID int,
	FOREIGN KEY (SchoolID) REFERENCES SCHOOL (SchoolID)
);

CREATE TABLE SCHOOL_ENGAGEMENT_HISTORY (
    Date VARCHAR(60),
    SchoolID int,
	FOREIGN KEY (SchoolID) REFERENCES SCHOOL (SchoolID)
);

CREATE TABLE SCHOOL_COMMUNICATION (
    Date VARCHAR(60),
    Message VARCHAR(200),
    SchoolID int,
	FOREIGN KEY (SchoolID) REFERENCES SCHOOL (SchoolID)
);

CREATE TABLE SCHOOL_STUDENT_ACTIVITIES (
	ActivitiesID int AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(40),
    Email VARCHAR(100),
    SchoolID int,
	FOREIGN KEY (SchoolID) REFERENCES SCHOOL (SchoolID)
);

CREATE TABLE SCHOOL_CONTACTS (
	SchoolContactID int AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(40),
    Email VARCHAR(100),
    SchoolID int,
	FOREIGN KEY (SchoolID) REFERENCES SCHOOL (SchoolID)
);

CREATE TABLE SCHOOL_PHONE (
    Phone VARCHAR(30),
    SchoolContactID int,
	FOREIGN KEY (SchoolContactID) REFERENCES SCHOOL_CONTACTS (SchoolContactID)
);

CREATE TABLE PARTNER (
    PartnerID int AUTO_INCREMENT PRIMARY KEY,
    OrganizationName varchar(50)
);

CREATE TABLE AFFILIATED_WITH (
    SchoolID int,
    PartnerID int,
    FOREIGN KEY (SchoolID) REFERENCES SCHOOL (SchoolID),
	FOREIGN KEY (PartnerID) REFERENCES PARTNER (PartnerID)
);

CREATE TABLE PARTNER_COMMUNICATION (
    Date VARCHAR(60),
    Message VARCHAR(200),
    PartnerID int,
	FOREIGN KEY (PartnerID) REFERENCES PARTNER (PartnerID)
);

CREATE TABLE PARTNER_HISTORY (
    Date VARCHAR(60),
    Message VARCHAR(200),
    PartnerID int,
	FOREIGN KEY (PartnerID) REFERENCES PARTNER (PartnerID)
);

CREATE TABLE PARTNER_CONTACTS (
    PartnerContactID int AUTO_INCREMENT PRIMARY KEY,
    Name varchar(50),
    PartnerID int,
    FOREIGN KEY (PartnerID) REFERENCES PARTNER (PartnerID)
);

CREATE TABLE PARTNER_PHONE (
    Phone VARCHAR(30),
    PartnerContactID int,
	FOREIGN KEY (PartnerContactID) REFERENCES PARTNER_CONTACTS (PartnerContactID)
);

CREATE TABLE PARTNER_EMAIL (
    Email VARCHAR(100),
    PartnerContactID int,
	FOREIGN KEY (PartnerContactID) REFERENCES PARTNER_CONTACTS (PartnerContactID)
);
*/
/*
ALTER TABLE SCHOOL_ASSOCIATION
DROP COLUMN Name;

ALTER TABLE SCHOOL_ASSOCIATION
ADD COLUMN Name varchar(50);

ALTER TABLE SCHOOL_ENGAGEMENT_HISTORY
DROP COLUMN History;

ALTER TABLE SCHOOL_ENGAGEMENT_HISTORY
ADD COLUMN History varchar(250);

ALTER TABLE SCHOOL_COMMUNICATION
DROP COLUMN Communication;

ALTER TABLE SCHOOL_COMMUNICATION
ADD COLUMN Communication varchar(250);
*/
